# -*- coding: utf-8 -*-
"""thai con

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jt9uSxicRcNg8cUB6D_Hl0uRagFWPVb9
"""

import tkinter as tk
import random

# Define the consonants and their names
consonants = [
    ("ก", "gor kai"),
    ("ข", "khor khai"),
    ("ฃ", "khor khuat"),
    ("ค", "khor khon"),
    ("ฅ", "khor rakhang"),
    ("ฆ", "khor khwang"),
    ("ง", "ngor ngoo"),
    ("จ", "jor jaan"),
    ("ฉ", "chor ching"),
    ("ช", "chor chang"),
    ("ซ", "sor so"),
    ("ฌ", "chor chao"),
    ("ญ", "yor ying"),
    ("ฎ", "dor cha da"),
    ("ฏ", "tor tak"),
    ("ฐ", "thor than"),
    ("ฑ", "thor thung"),
    ("ฒ", "thor thahan"),
    ("ณ", "nor nu"),
    ("ด", "dor dek"),
    ("ต", "tor tao"),
    ("ถ", "thor thung"),
    ("ท", "thor thong"),
    ("ธ", "thor thong"),
    ("น", "nor neen")
]

# Create the root window
root = tk.Tk()
root.title("Thai Consonant Flashcards")
root.geometry("400x300")

# Set up the card frame
frame = tk.Frame(root, width=300, height=200, bg="lightblue")
frame.pack_propagate(False)  # Prevent the frame from shrinking to fit its content
frame.pack(pady=50)

# Label to display consonants or names
label = tk.Label(frame, text="", font=("Arial", 50), bg="lightblue")
label.pack(expand=True)

# Function to flip the card
def flip_card():
    global is_showing_name, current_card
    if is_showing_name:
        # Show the consonant
        label.config(text=current_card[0])
    else:
        # Show the name
        label.config(text=current_card[1])
    is_showing_name = not is_showing_name

# Function to show a new card
def next_card():
    global current_card, is_showing_name
    current_card = random.choice(consonants)
    label.config(text=current_card[0])
    is_showing_name = False

# Add a button to flip the card
flip_button = tk.Button(root, text="Flip", command=flip_card, font=("Arial", 16))
flip_button.pack(side="left", padx=20)

# Add a button to go to the next card
next_button = tk.Button(root, text="Next", command=next_card, font=("Arial", 16))
next_button.pack(side="right", padx=20)

# Initialize the game
is_showing_name = False
current_card = random.choice(consonants)
label.config(text=current_card[0])

# Start the Tkinter main loop
root.mainloop()